FROM python:3.7
ENV PYTHONUNBUFFERED 1
RUN mkdir /code
WORKDIR /code
RUN apt-get update -y && apt-get install -y libmemcached-dev zlib1g-dev libssl-dev libffi-dev python-dev build-essential
ADD requirements.txt /code/
RUN pip install -r requirements.txt
ADD . /code/
RUN python manage.py collectstatic --noinput
CMD gunicorn --bind 0.0.0.0:8000 hubspotyealink.wsgi --log-file -